services:
  freetar:
    image: kmille2/freetar:latest
    build: .
    container_name: freetar
    ports:
      - "${FREETAR_PORT:-22000}:22000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
